# Generated by Django 6.0.4 on 2026-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kid_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
        migrations.AddField(
            model_name='family',
            name='family_name',
            field=models.CharField(default='Unknown Family', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
