# Generated by Django 6.0.4 on 2026-05-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.team'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(choices=[('family_join_request', 'Family_Join Request'), ('family_sent_invite', 'Family_Sent Invite'), ('team_join_request', 'Team_Join_Request'), ('team_sent_invite', 'Team_Sent_Invite')], default='family_join_request', max_length=20),
        ),
    ]
