# Generated by Django 6.0.4 on 2026-05-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invite_unique_together_invite_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamInvite',
        ),
    ]
