# Generated by Django 6.0.4 on 2026-04-25 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_kid_name_remove_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kid_attending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.kid'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='core.family'),
        ),
    ]
