# Generated by Django 6.0.4 on 2026-04-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_family_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='core.family'),
        ),
    ]
