# Generated by Django 6.0.4 on 2026-05-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_teaminvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.family'),
        ),
    ]
