# Generated by Django 6.0.4 on 2026-05-05 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_family_options_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='invited_user',
            new_name='inviter',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='invited_by',
            new_name='requester',
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('family', 'requester')},
        ),
    ]
