# Generated by Django 6.0.4 on 2026-05-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teamevent_teameventattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teameventinvitation',
            name='team_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.teamevent'),
        ),
    ]
