# Generated by Django 6.0.4 on 2026-05-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_event_team_teammembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kid')),
                ('team_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.teammembership')),
            ],
        ),
    ]
