# Generated by Django 6.0.4 on 2026-05-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_team_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='original_team_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
