# Generated by Django 6.0.4 on 2026-05-18 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_teammembership_role_teaminvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='inviter',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='requester',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('family', 'receiver')},
        ),
    ]
