# Generated by Django 6.0.4 on 2026-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_event_is_team_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('team_event_updated', 'Team Event Updated'), ('team_event_canceled', 'Team Event Canceled'), ('team_event_reminder', 'Team Event Reminder'), ('invitation', 'New Invitation'), ('personal_event_conflict', 'Personal Event Conflict'), ('account', 'Account Update'), ('family', 'Family Update')], default='general', max_length=50),
        ),
    ]
