# Generated by Django 6.0.4 on 2026-05-18 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_inviter_invite_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('sent_invite', 'Sent Invite')], default='join_request', max_length=20),
        ),
    ]
