# Generated by Django 6.0.4 on 2026-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification_extra_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('team_event_updated', 'Team Event Updated'), ('team_event_canceled', 'Team Event Canceled'), ('team_event_reminder', 'Team Event Reminder'), ('team_event_invitation', 'Team Event Invitation'), ('family_invitation', 'Family Invitation'), ('personal_event_conflict', 'Personal Event Conflict'), ('account', 'Account Update'), ('family', 'Family Update')], default='general', max_length=50),
        ),
    ]
