# Generated by Django 6.0.4 on 2026-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teameventattendance',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('team_event_updated', 'Team Event Updated'), ('team_event_canceled', 'Team Event Canceled'), ('team_event_reminder', 'Team Event Reminder'), ('team_event_invitation', 'Team Event Invitation'), ('family_invitation', 'Family Invitation'), ('personal_event_conflict', 'Personal Event Conflict'), ('account', 'Account Update'), ('family', 'Family Update'), ('roster_request', 'Roster Request'), ('team_invite', 'Team Invite'), ('parent_invite', 'Parent Invite')], default='general', max_length=50),
        ),
    ]
