# Generated by Django 6.0.4 on 2026-05-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teameventattendance_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
