# Generated by Django 6.0.4 on 2026-05-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_extra_data_to_invite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('family', 'receiver')},
        ),
    ]
