# Generated by Django 6.0.4 on 2026-05-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_one_family_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to='core.family'),
        ),
    ]
