# Generated by Django 6.0.4 on 2026-05-29 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_parent_reverse_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kid_attending',
        ),
        migrations.AddField(
            model_name='event',
            name='attending_parents',
            field=models.ManyToManyField(blank=True, related_name='attending_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='kids',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.kid'),
        ),
    ]
