# Generated by Django 6.0.4 on 2026-05-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_multi_kid_and_parent_attending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleToken',
        ),
    ]
