# Generated by Django 6.0.4 on 2026-05-31 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_google_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterRequestKid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_kids', to='core.invite')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kid')),
            ],
            options={
                'unique_together': {('invite', 'kid')},
            },
        ),
    ]
