# Generated by Django 6.0.4 on 2026-05-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_roster_request_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('team_event_updated', 'Team Event Updated'), ('team_event_canceled', 'Team Event Canceled'), ('team_event_reminder', 'Team Event Reminder'), ('team_event_invitation', 'Team Event Invitation'), ('family_invitation', 'Family Invitation'), ('family_join_request', 'Family Join Request'), ('personal_event_conflict', 'Personal Event Conflict'), ('account', 'Account Update'), ('family', 'Family Update'), ('roster_request', 'Roster Request'), ('team_invite', 'Team Invite'), ('parent_invite', 'Parent Invite')], default='general', max_length=50),
        ),
    ]
