# Generated by Django 6.0.4 on 2026-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cleanup_roster_request_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced by Team Event'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
