# Generated by Django 6.0.4 on 2026-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='color',
            field=models.CharField(default='#3b82f6', help_text='Hex color for timeline and badges (e.g. #3b82f6)', max_length=9),
        ),
    ]
