# Generated by Django 6.0.4 on 2026-06-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_kid_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
