# Generated by Django 6.0.4 on 2026-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_event_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for parents (used in owner roster views)', max_length=20, null=True),
        ),
    ]
