# Generated by Django 6.0.4 on 2026-06-05 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_profile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(help_text='Original User PK at time of deletion')),
                ('username', models.CharField(blank=True, help_text='Username at deletion time (for internal audit only)', max_length=150)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Deletion Log',
                'verbose_name_plural': 'Account Deletion Logs',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='data_consent_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when user explicitly consented to data processing (incl. children's data) per Privacy Policy.", null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Original creator; set to NULL on account deletion to preserve family for other members (right to be forgotten compliance).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
