# Generated by Django 6.0.4 on 2026-06-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_accountdeletionlog_profile_data_consent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for parents (used in owner roster views)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='America/Chicago', help_text="IANA timezone name (e.g. America/Chicago). Auto-detected at signup from the user's browser.", max_length=50),
        ),
    ]
