# Generated by Django 6.0.4 on 2026-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_profile_phone_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#3b82f6', help_text='Hex color for badges (super distinct per team)', max_length=9),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_type',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('soccer', 'Soccer'), ('football', 'Football')], max_length=100),
        ),
    ]
