# Generated by Django 6.0.4 on 2026-06-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevent',
            name='event_type',
            field=models.CharField(choices=[('team', 'Team Event'), ('training', 'Training Session')], default='team', max_length=20),
        ),
        migrations.AlterField(
            model_name='teameventattendance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='accepted', max_length=20),
        ),
    ]
