# Generated by Django 6.0.4 on 2026-06-19 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_teamevent_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to='core.team'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='core_event_start_t_61b12a_idx'),
        ),
        migrations.AddIndex(
            model_name='teamevent',
            index=models.Index(fields=['start_time'], name='core_teamev_start_t_83fcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='teamevent',
            index=models.Index(fields=['team', 'start_time'], name='core_teamev_team_id_3d11a7_idx'),
        ),
        migrations.AddIndex(
            model_name='teameventattendance',
            index=models.Index(fields=['status'], name='core_teamev_status_a20fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='teameventattendance',
            index=models.Index(fields=['team_event', 'status'], name='core_teamev_team_ev_3254b0_idx'),
        ),
    ]
