from django.urls import path
from . import views


urlpatterns = [
    path('add_event/', views.add_event, name = 'add_event'),
    path('edit_event/<int:event_id>/', views.edit_event, name = 'edit_event'),
    path('', views.event_list, name='event_list'),
    # Unified delete view that can handle different types
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('delete_attendance/<int:attendance_id>/', views.delete_event, name='delete_attendance'),  # for team events
    path('delete_team_event/<int:team_event_id>/', views.delete_event, name='delete_team_event'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signup/', views.signup_view, name='signup' ),
    path('kid_list/', views.kid_list, name='kid_list'),
    path('add_kid/', views.add_kid, name='add_kid'),
    path('edit_kid/<int:kid_id>/', views.edit_kid, name='edit_kid'),
    path('delete_kid/<int:kid_id>/',views.delete_kid, name='delete_kid'),
    path('add_family/', views.add_family, name='add_family'),
    path('family_list/',views.family_list, name='family_list'),
    path('my-family/', views.my_family, name='my_family'),
    path('parent_teams/', views.parent_teams, name='parent_teams'),
    path('remove_kid_from_team/<int:team_id>/<int:kid_id>/', views.remove_kid_from_team, name='remove_kid_from_team'),
    path('create_first_family/', views.create_first_family, name='create_first_family'),
    path('invite_parent/<int:family_id>/', views.invite_parent, name='invite_parent'),
    path('family_invite_response/<int:invite_id>/', views.family_invite_response, name='family_invite_response'),
    path('remove_parent/<int:family_id>/<int:parent_id>', views.remove_parent, name='remove_parent'),
    path('family/<int:family_id>/', views.family_detail, name='family_detail'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('team-event/<int:event_id>/', views.team_event_detail, name='team_event_detail'),
    path('team/<int:team_id>/', views.team_detail, name='team_detail'),
    path('setup_family/', views.setup_family, name='setup_family'),
    path('parent-onboarding/', views.parent_onboarding, name='parent_onboarding'),
    path('owner-onboarding/', views.owner_onboarding, name='owner_onboarding'),
    path('join_family/', views.join_family, name='join_family'),
    path('accept_family_invite/<int:invite_id>/', views.accept_family_invite, name='accept_family_invite'),
    path('accept_team_invite/<int:invite_id>/', views.accept_team_invite, name='accept_team_invite'),
    path('decline_invite/<int:invite_id>/', views.decline_invite, name='decline_invite'),
    path('notifications/', views.notifications, name='notifications'),
    path('account_settings/', views.account_settings, name='account_settings'),
    path('change_password/', views.change_password, name='change_password'),
    path('create_team/', views.create_team, name='create_team'),
    path('team_list/', views.team_list, name='team_list'),
    path('edit_team/<int:team_id>/', views.edit_team, name='edit_team'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
    path('owner_remove_kid_from_team/<int:team_id>/<int:kid_id>/', views.owner_remove_kid_from_team, name='owner_remove_kid_from_team'),
    path('find_teams/', views.find_teams, name='find_teams'),
    path('owner_dashboard/', views.owner_dashboard, name='owner_dashboard'),
    path('players/', views.organization_players, name='org_players'),
    path('create_organization/', views.create_organization, name='create_organization'),
    path('team_invite_to_parent/<int:team_id>/<str:username>/', views.team_invite_to_parent, name='team_invite_to_parent'),
    path('parent_to_team_request/<int:team_id>/', views.parent_to_team_request, name='parent_to_team_request'),
    path('select_kids_for_team_join_request/<int:team_id>/', views.select_kids_for_team_join_request, name='select_kids_for_team_join_request'),
    path('team_to_parent_invite_search/<int:team_id>/', views.team_to_parent_invite_search, name='team_to_parent_invite_search'),
    path('organization_details/<int:org_id>/', views.organization_details, name='organization_details'),
    path('my-organization/', views.my_organization, name='my_organization'),
    path('add_team_event/', views.add_team_event, name='add_team_event'),
    path('decline_team_event_invite/<int:team_event_invitation_id>/<int:kid_id>/', views.decline_team_event_invite, name='decline_team_event_invite'),
    path('resolve_team_event_conflict/<int:team_event_invitation_id>/', views.resolve_team_event_conflict, name='resolve_team_event_conflict'),
    path('select_kids_for_team_roster/<int:invite_id>/', views.select_kids_for_team_roster, name='select_kids_for_team_roster'),
    path('review_roster_request/<int:invite_id>/', views.review_roster_request, name='review_roster_request'),
    path('team_event_kid_selection/<int:team_event_invitation_id>/', views.team_event_kid_selection, name='team_event_kid_selection'),
    path('replace_with_team_event/<int:team_event_invitation_id>/<int:kid_id>/', views.replace_with_team_event, name='replace_with_team_event'),
    path('edit_team_event/<int:event_id>/', views.edit_team_event, name = 'edit_team_event'),
    path('review-team-event-update/<int:event_id>/', views.review_team_event_update, name='review_team_event_update'),
    path('keep-team-event-update/<int:event_id>/', views.keep_team_event_update, name='keep_team_event_update'),
    path('remove-team-event-attendance/<int:event_id>/', views.remove_team_event_attendance, name='remove_team_event_attendance'),
    path('team_invite_response/<int:invite_id>/', views.team_invite_response, name='team_invite_response'),

    # Step 3: Privacy, Data Export, Account Deletion, Legal
    path('account/export/', views.export_data, name='export_data'),
    path('account/delete/', views.delete_account, name='delete_account'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('terms/', views.terms_of_service, name='terms_of_service'),
]